// ---------------------------------------------------------------------------
// Sculptor V1 — Architect Agent (Phase 2: structured)
//
// Generates document structure (outline) from confirmed Intent, Audience,
// and Constraint layers. Validates alignment with core_message and supports
// refinement based on user feedback.
// ---------------------------------------------------------------------------

import { BaseAgent } from './types';
import { createAgentResponse, startTimer } from './base-agent';
import type { AgentRequest, AgentResponse, IPCSAccessor, ProposalMutation } from './types';
import { LLMClient } from '@/lib/llm-client';
import { AlgorithmRunner } from '@/lib/algorithm-runner';
import { checkAlignment } from '@/algorithms/intent-blueprint-alignment';
import type { AlignmentResult } from '@/algorithms/intent-blueprint-alignment';
import { ARCHITECT_STRUCTURE_PROMPT } from '@/prompts/architect-agent';
import type { PCSState, StructureSection } from '@/pcs/types';

// ---------------------------------------------------------------------------
// Shared instances
// ---------------------------------------------------------------------------

const llmClient = new LLMClient();
const algorithmRunner = new AlgorithmRunner();

// ---------------------------------------------------------------------------
// ArchitectAgent
// ---------------------------------------------------------------------------

export class ArchitectAgent extends BaseAgent {
  constructor(pcs: IPCSAccessor) {
    super('architect', pcs);
  }

  async execute(request: AgentRequest): Promise<AgentResponse> {
    const stop = startTimer();
    const action = request.action;
    const snapshot = request.pcsSnapshot;

    switch (action) {
      // ── generate_structure ────────────────────────────────────────
      case 'generate_structure': {
        let llmCalls = 0;
        let tokensUsed = 0;
        let structure: StructureSection[] = [];

        try {
          const variables: Record<string, unknown> = {
            intent_summary: buildIntentSummary(snapshot),
            audience_summary: buildAudienceSummary(snapshot),
            constraint_summary: buildConstraintSummary(snapshot),
            format_type: snapshot.constraint.type.value || '文章',
            tone_description: snapshot.expression.tone.value || '专业、清晰',
            audience_context: snapshot.audience.audience_type.value || '普通读者',
          };

          const systemPrompt = ARCHITECT_STRUCTURE_PROMPT.systemPrompt ?? '';
          let prompt = ARCHITECT_STRUCTURE_PROMPT.template;
          for (const [key, val] of Object.entries(variables)) {
            prompt = prompt.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), String(val));
          }

          const response = await llmClient.complete({
            prompt,
            systemPrompt,
            responseFormat: 'json',
            maxTokens: ARCHITECT_STRUCTURE_PROMPT.maxTokens,
          });

          llmCalls = 1;
          tokensUsed = response.usage.totalTokens;

          if (response.json && typeof response.json === 'object') {
            const json = response.json as Record<string, unknown>;
            const rawStructure = Array.isArray(json['structure']) ? json['structure'] : [];
            structure = rawStructure.map((item: Record<string, unknown>, index: number) => ({
              id: typeof item['id'] === 'string' ? item['id'] : `section-${index + 1}`,
              title: typeof item['title'] === 'string' ? item['title'] : `章节 ${index + 1}`,
              goal: typeof item['goal'] === 'string' ? item['goal'] : '',
              function: isValidNodeFunction(item['function'])
                ? (item['function'] as StructureSection['function'])
                : 'argument',
              hardness: item['hardness'] === 'soft' ? 'soft' : 'hard',
              draft_state: 'empty' as const,
              content_draft: '',
              pcs_status: 'proposed' as const,
              source: 'ai' as const,
              confidence: 0.7,
              order: index,
            }));
          }
        } catch {
          // Rule-based fallback: minimal structure from core_message
          structure = buildFallbackStructure(snapshot);
        }

        const mutations: ProposalMutation[] = [];

        for (const section of structure) {
          mutations.push({
            fieldPath: `structure.sections.${section.order}`,
            proposedValue: section,
            reason: 'Generated by Architect Agent based on intent + constraints',
            trigger: 'manual',
            confidence: llmCalls > 0 ? 0.7 : 0.4,
          });
        }

        const latency = stop();
        return createAgentResponse('architect', action, {
          result: {
            structure,
            sectionCount: structure.length,
            method: llmCalls > 0 ? 'llm' : 'rule-based',
          },
          pcsMutations: mutations,
          nextActions: ['validate_alignment'],
          latency,
          llmCalls,
          tokensUsed,
        });
      }

      // ── validate_alignment ────────────────────────────────────────
      case 'validate_alignment': {
        const alignmentResult = await algorithmRunner.run<AlignmentResult>(
          { name: 'intent-blueprint-alignment' },
          () => Promise.resolve(checkAlignment(snapshot)),
        );

        const alignment =
          alignmentResult.success && alignmentResult.data
            ? alignmentResult.data
            : {
                overallScore: 0,
                coreMessageCovered: false,
                uncoveredAspects: [],
                sectionScores: [],
                recommendations: ['对齐检查失败，请手动验证。'],
              };

        const nextActions = alignment.coreMessageCovered
          ? ['approve_structure']
          : ['refine_structure'];

        const latency = stop();
        return createAgentResponse('architect', action, {
          result: { alignment },
          nextActions,
          latency,
        });
      }

      // ── refine_structure ──────────────────────────────────────────
      case 'refine_structure': {
        const feedback = typeof request.payload === 'string' ? request.payload : '';

        // In V1, refinement passes feedback back to the caller for another
        // generate_structure round. We produce an updated structure proposal.
        const mutations: ProposalMutation[] = [];

        if (feedback.length > 0) {
          mutations.push({
            fieldPath: 'structure.sections',
            proposedValue: snapshot.structure.sections,
            reason: `User feedback applied during refinement: "${feedback.slice(0, 100)}"`,
            trigger: 'manual',
            confidence: 0.8,
          });
        }

        const latency = stop();
        return createAgentResponse('architect', action, {
          result: { feedback, existingSections: snapshot.structure.sections.length },
          pcsMutations: mutations,
          nextActions: ['generate_structure'],
          latency,
        });
      }

      default:
        return createAgentResponse('architect', action, {
          result: { error: `Unknown action: ${action}` },
          latency: stop(),
        });
    }
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildIntentSummary(state: PCSState): string {
  return [
    `目的: ${state.intent.purpose.value || '未指定'}`,
    `核心信息: ${state.intent.core_message.value || '未指定'}`,
    `预期影响: ${state.intent.desired_impact.value || '未指定'}`,
    `目标情感: ${state.intent.target_emotion.value || '未指定'}`,
  ].join('\n');
}

function buildAudienceSummary(state: PCSState): string {
  return [
    `读者类型: ${state.audience.audience_type.value || '未指定'}`,
    `知识水平: ${state.audience.knowledge_level.value || '未指定'}`,
    `关系: ${state.audience.relationship.value || '未指定'}`,
    `痛点: ${state.audience.pain_points.value.join('、') || '未指定'}`,
  ].join('\n');
}

function buildConstraintSummary(state: PCSState): string {
  return [
    `类型: ${state.constraint.type.value || '未指定'}`,
    `平台: ${state.constraint.platform.value || '未指定'}`,
    `格式: ${state.constraint.format.value || '未指定'}`,
    `字数范围: ${state.constraint.length_min.value || 0}–${state.constraint.length_max.value || '不限'}`,
  ].join('\n');
}

const VALID_NODE_FUNCTIONS = new Set<string>([
  'introduce',
  'argument',
  'evidence',
  'counter',
  'transition',
  'conclude',
  'elaborate',
]);

function isValidNodeFunction(value: unknown): boolean {
  return typeof value === 'string' && VALID_NODE_FUNCTIONS.has(value);
}

function buildFallbackStructure(state: PCSState): StructureSection[] {
  const coreMessage = state.intent.core_message.value || '未命名主题';
  return [
    {
      id: 'section-1',
      title: '引言',
      goal: `引出主题：${coreMessage}`,
      function: 'introduce',
      hardness: 'hard',
      draft_state: 'empty',
      content_draft: '',
      pcs_status: 'proposed',
      source: 'ai',
      confidence: 0.4,
      order: 0,
    },
    {
      id: 'section-2',
      title: '主体论述',
      goal: `深入阐述：${coreMessage}`,
      function: 'argument',
      hardness: 'hard',
      draft_state: 'empty',
      content_draft: '',
      pcs_status: 'proposed',
      source: 'ai',
      confidence: 0.4,
      order: 1,
    },
    {
      id: 'section-3',
      title: '总结',
      goal: `总结要点并与${coreMessage}呼应`,
      function: 'conclude',
      hardness: 'hard',
      draft_state: 'empty',
      content_draft: '',
      pcs_status: 'proposed',
      source: 'ai',
      confidence: 0.4,
      order: 2,
    },
  ];
}
