// ---------------------------------------------------------------------------
// Sculptor V1 — Scribe Agent (Phase 3–4: executing)
//
// Generates prose content for individual sections, revises existing content,
// checks consistency against constraints, and discovers stylistic fingerprints
// from reference texts.
// ---------------------------------------------------------------------------

import { BaseAgent } from './types';
import { createAgentResponse, startTimer } from './base-agent';
import type { AgentRequest, AgentResponse, IPCSAccessor, ProposalMutation } from './types';
import { LLMClient } from '@/lib/llm-client';
import { AlgorithmRunner } from '@/lib/algorithm-runner';
import { assembleNodeContext, generatePlan } from '@/algorithms/generation-planning';
import { checkAdhesion, checkGiantNode } from '@/algorithms/node-context-assembler';
import { checkConstraints } from '@/algorithms/constraint-checker';
import { detectMissingInfo } from '@/algorithms/missing-info-detector';
import { discoverStyle } from '@/algorithms/style-discovery';
import { analyzeStyleChange } from '@/algorithms/style-evolution';
import { analyzeRevision } from '@/algorithms/revision-impact-analyzer';
import {
  SCRIBE_GENERATE_PROMPT,
  SCRIBE_REVISE_PROMPT,
  SCRIBE_CHECK_PROMPT,
} from '@/prompts/scribe-agent';
import type { PCSState } from '@/pcs/types';

// ---------------------------------------------------------------------------
// Shared instances
// ---------------------------------------------------------------------------

const llmClient = new LLMClient();
const algorithmRunner = new AlgorithmRunner();

// ---------------------------------------------------------------------------
// ScribeAgent
// ---------------------------------------------------------------------------

export class ScribeAgent extends BaseAgent {
  constructor(pcs: IPCSAccessor) {
    super('scribe', pcs);
  }

  async execute(request: AgentRequest): Promise<AgentResponse> {
    const stop = startTimer();
    const action = request.action;
    const snapshot = request.pcsSnapshot;
    const payload = request.payload as Record<string, unknown> | null;

    switch (action) {
      // ── generate ──────────────────────────────────────────────────
      case 'generate': {
        const nodeId = typeof payload?.['nodeId'] === 'string' ? payload['nodeId'] : '';
        if (!nodeId) {
          const latency = stop();
          return createAgentResponse('scribe', action, {
            result: { error: 'Missing nodeId in payload' },
            latency,
          });
        }

        let llmCalls = 0;
        let tokensUsed = 0;
        let content = '';

        try {
          const plan = generatePlan(snapshot, nodeId);
          const context = assembleNodeContext(snapshot, nodeId);

          const variables: Record<string, unknown> = {
            intent_purpose: snapshot.intent.purpose.value || '',
            intent_core_message: snapshot.intent.core_message.value || '',
            audience_context: context.audienceContext || '普通读者',
            tone_description: context.toneDescription || '专业',
            avoid_list: context.avoidList.join('、') || '无',
            node_goal: plan.goal_summary,
            node_function: context.node.function,
            estimated_length: String(plan.estimated_length),
            previous_context: plan.transition_from,
            next_context: plan.transition_to,
            required_topics: plan.required_topics.join('、') || '无',
            style_reference: context.styleReference || '无',
            format_reference: snapshot.expression.format_reference.value || '无',
          };

          const systemPrompt = SCRIBE_GENERATE_PROMPT.systemPrompt ?? '';
          let prompt = SCRIBE_GENERATE_PROMPT.template;
          for (const [key, val] of Object.entries(variables)) {
            prompt = prompt.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), String(val));
          }

          const response = await llmClient.complete({
            prompt,
            systemPrompt,
            maxTokens: SCRIBE_GENERATE_PROMPT.maxTokens,
          });

          llmCalls = 1;
          tokensUsed = response.usage.totalTokens;
          content = response.text;
        } catch {
          // Rule-based fallback: generate placeholder content
          content = buildFallbackContent(snapshot, nodeId);
        }

        const mutations: ProposalMutation[] = [
          {
            fieldPath: `structure.sections.${findSectionIndex(snapshot, nodeId)}.content_draft`,
            proposedValue: content,
            reason: `Generated by Scribe Agent for node: ${nodeId}`,
            trigger: 'manual',
            confidence: llmCalls > 0 ? 0.7 : 0.3,
          },
        ];

        const latency = stop();
        return createAgentResponse('scribe', action, {
          result: { nodeId, content, contentLength: content.length },
          pcsMutations: mutations,
          nextActions: ['check'],
          latency,
          llmCalls,
          tokensUsed,
        });
      }

      // ── revise ────────────────────────────────────────────────────
      case 'revise': {
        const operation =
          typeof payload?.['operation'] === 'string' ? payload['operation'] : 'rewrite';
        const originalText =
          typeof payload?.['originalText'] === 'string' ? payload['originalText'] : '';
        const instruction =
          typeof payload?.['instruction'] === 'string' ? payload['instruction'] : '';

        let llmCalls = 0;
        let tokensUsed = 0;
        let revisedText = originalText;

        try {
          const variables: Record<string, unknown> = {
            operation,
            original_text: originalText,
            instruction: instruction || '请优化内容',
            tone_description: snapshot.expression.tone.value || '专业',
            avoid_list: snapshot.expression.avoid.value.join('、') || '无',
          };

          const systemPrompt = SCRIBE_REVISE_PROMPT.systemPrompt ?? '';
          let prompt = SCRIBE_REVISE_PROMPT.template;
          for (const [key, val] of Object.entries(variables)) {
            prompt = prompt.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), String(val));
          }

          const response = await llmClient.complete({
            prompt,
            systemPrompt,
            maxTokens: SCRIBE_REVISE_PROMPT.maxTokens,
          });

          llmCalls = 1;
          tokensUsed = response.usage.totalTokens;
          revisedText = response.text;
        } catch {
          // Rule-based fallback for simple operations
          revisedText = applySimpleRevision(originalText, operation);
        }

        // Analyze revision impact
        const impact = analyzeRevision(
          (payload?.['nodeId'] as string) ?? '',
          originalText,
          revisedText,
          snapshot,
        );

        const latency = stop();
        return createAgentResponse('scribe', action, {
          result: {
            operation,
            originalLength: originalText.length,
            revisedLength: revisedText.length,
            revisedText,
            impact,
          },
          pcsMutations: [],
          nextActions: impact.requiresProposal ? ['propose_intent_update'] : ['check'],
          latency,
          llmCalls,
          tokensUsed,
        });
      }

      // ── check ─────────────────────────────────────────────────────
      case 'check': {
        const content = typeof payload?.['content'] === 'string' ? payload['content'] : '';
        const nodeId = typeof payload?.['nodeId'] === 'string' ? payload['nodeId'] : '';

        // Run constraint checker
        const constraintResult = await algorithmRunner.run({ name: 'constraint-checker' }, () =>
          Promise.resolve(checkConstraints(content, snapshot, nodeId)),
        );

        // Run missing-info detector
        const missingInfoResult = await algorithmRunner.run({ name: 'missing-info-detector' }, () =>
          Promise.resolve(detectMissingInfo(content, snapshot, nodeId)),
        );

        // Run adhesion check
        const adhesionResult = await algorithmRunner.run(
          { name: 'node-context-assembler-adhesion' },
          () => Promise.resolve(checkAdhesion(snapshot, nodeId)),
        );

        // Run giant node check
        const giantNodeResult = await algorithmRunner.run(
          { name: 'node-context-assembler-giant' },
          () => Promise.resolve(checkGiantNode(snapshot, nodeId)),
        );

        // Try LLM-based consistency check for deeper analysis
        let llmCalls = 0;
        let tokensUsed = 0;
        let llmCheckResult: unknown = null;

        try {
          const variables: Record<string, unknown> = {
            content,
            intent_core_message: snapshot.intent.core_message.value || '',
            tone_description: snapshot.expression.tone.value || '专业',
            avoid_list: snapshot.expression.avoid.value.join('、') || '无',
            required_topics:
              snapshot.knowledge.required_topics
                .filter((t) => t.section_id === nodeId && !t.covered)
                .map((t) => t.topic)
                .join('、') || '无',
          };

          const systemPrompt = SCRIBE_CHECK_PROMPT.systemPrompt ?? '';
          let prompt = SCRIBE_CHECK_PROMPT.template;
          for (const [key, val] of Object.entries(variables)) {
            prompt = prompt.replace(new RegExp(`\\{\\{${key}\\}\\}`, 'g'), String(val));
          }

          const response = await llmClient.complete({
            prompt,
            systemPrompt,
            responseFormat: 'json',
            maxTokens: SCRIBE_CHECK_PROMPT.maxTokens,
          });

          llmCalls = 1;
          tokensUsed = response.usage.totalTokens;
          llmCheckResult = response.json;
        } catch {
          // LLM check failed — rule-based results already captured above
        }

        const allPassed =
          constraintResult.success &&
          constraintResult.data?.passed !== false &&
          missingInfoResult.success &&
          (missingInfoResult.data?.newGaps.length ?? 0) === 0;

        const latency = stop();
        return createAgentResponse('scribe', action, {
          result: {
            nodeId,
            constraintCheck: constraintResult.success ? constraintResult.data : null,
            missingInfo: missingInfoResult.success ? missingInfoResult.data : null,
            adhesion: adhesionResult.success ? adhesionResult.data : null,
            giantNode: giantNodeResult.success ? giantNodeResult.data : null,
            llmCheck: llmCheckResult,
            allPassed,
          },
          nextActions: allPassed ? ['approve_node'] : ['revise'],
          latency,
          llmCalls,
          tokensUsed,
        });
      }

      // ── discover_style ────────────────────────────────────────────
      case 'discover_style': {
        const sampleTexts: string[] = Array.isArray(payload?.['sampleTexts'])
          ? (payload?.['sampleTexts'] as string[])
          : [];

        const fingerprintResult = await algorithmRunner.run({ name: 'style-discovery' }, () =>
          Promise.resolve(discoverStyle(sampleTexts)),
        );

        const fingerprint =
          fingerprintResult.success && fingerprintResult.data ? fingerprintResult.data : null;

        // If confidence is high enough, analyze style change for expression.tone
        const mutations: ProposalMutation[] = [];
        if (fingerprint && fingerprint.confidence > 0.5) {
          const styleChange = analyzeStyleChange(
            'tone',
            snapshot.expression.tone.value,
            fingerprint.tone,
            { occurrenceCount: sampleTexts.length, consistencyScore: fingerprint.confidence },
          );

          if (styleChange.autoApply) {
            mutations.push({
              fieldPath: 'expression.tone',
              proposedValue: fingerprint.tone,
              reason: styleChange.reason,
              trigger: 'manual',
              confidence: fingerprint.confidence,
            });
          }
        }

        const latency = stop();
        return createAgentResponse('scribe', action, {
          result: { fingerprint },
          pcsMutations: mutations,
          nextActions: ['check'],
          latency,
        });
      }

      default:
        return createAgentResponse('scribe', action, {
          result: { error: `Unknown action: ${action}` },
          latency: stop(),
        });
    }
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function findSectionIndex(state: PCSState, nodeId: string): number {
  const idx = state.structure.sections.findIndex((s) => s.id === nodeId);
  return idx >= 0 ? idx : 0;
}

function buildFallbackContent(state: PCSState, nodeId: string): string {
  const section = state.structure.sections.find((s) => s.id === nodeId);
  const coreMessage = state.intent.core_message.value || '主题';
  const title = section?.title ?? '章节';
  const goal = section?.goal ?? '展开论述';

  return `【${title}】\n\n本节围绕「${coreMessage}」展开，目标：${goal}。\n\n（此为 V1 规则生成的占位内容，将在 LLM 接入后替换为正式文本。）`;
}

function applySimpleRevision(text: string, operation: string): string {
  switch (operation) {
    case 'condense': {
      const sentences = text.split(/[。！？.!?]/).filter(Boolean);
      return sentences.slice(0, Math.ceil(sentences.length / 2)).join('。') + '。';
    }
    case 'expand':
      return text + '\n\n（补充说明：以上内容经 V1 规则扩展，添加了额外的背景信息。）';
    case 'retone':
      return text; // V1: tone adjustment requires LLM
    default:
      return text;
  }
}
